#!/usr/bin/env python

# Copyright 2010 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""
XenAPI Plugin for transfering data between host nodes
"""

import os.path
import subprocess

import XenAPIPlugin

SSH_HOSTS = '/root/.ssh/known_hosts'
DEVNULL = '/dev/null'
KEYSCAN = '/usr/bin/ssh-keyscan'
RSYNC = '/usr/bin/rsync'

def _key_scan_and_add(host):
    """SSH scans a remote host and writes the SSH key out to known_hosts"""
    # Touch the file if it doesn't yet exist
    open(SSH_HOSTS, 'a').close()

    null = open(DEVNULL, 'w')
    known_hosts = open(SSH_HOSTS, 'a')
    key = subprocess.Popen(['/usr/bin/ssh-keyscan', '-t', 'rsa', host],
            stdout=subprocess.PIPE, stderr=null).communicate()[0].strip()
    grep = subprocess.call(['/bin/grep', '-o', '%s' % key, SSH_HOSTS], 
            stdout=null, stderr=null)
    if grep == 1:
        known_hosts.write(key)
    null.close()
    known_hosts.close()

def transfer_file(host, file_path):
    """Rsyncs a VHD to an adjacent host"""
    _key_scan_and_add(host)
    if subprocess.call([RSYNC, file_path, "%s:/root/" % host]) != 0:
        raise Exception("Unexpected VHD transfer failure")

if __name__ == '__main__':
    XenAPIPlugin.dispatch({'transfer_file': transfer_file})
