#!/usr/bin/env python

# Copyright 2010 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""
XenAPI Plugin for transfering data between host nodes
"""

import os.path
import pickle
import subprocess

import XenAPIPlugin

SSH_HOSTS = '/root/.ssh/known_hosts'
DEVNULL = '/dev/null'
KEYSCAN = '/usr/bin/ssh-keyscan'
RSYNC = '/usr/bin/rsync'


def transfer_vhd(session, args):
    """Rsyncs a VHD to an adjacent host"""
    params = pickle.dumps(args)
    instance_id = params['instance_id']
    host = params['host']
    vdi_uuid = params['vdi_uuid']
    sr_path = get_sr_path(session)
    vhd_path = "%s.vhd" % vdi_uuid

    source_path = "%s/%s" % (sr_path, vhd_path)
    dest_path = '%s:/images/instance%d/' % (host, instance_id)
    rsync_args = [['nohup', RSYNC, '-av', '--progress', 
            '-e "ssh -o StrictHostKeyChecking=no"', source_path, dest_path]

    if subprocess.call(rsync_args) != 0:
        raise Exception("Unexpected VHD transfer failure")

if __name__ == '__main__':
    XenAPIPlugin.dispatch({'transfer_vhd': transfer_vhd})
