#!/usr/bin/env python

# Copyright (c) 2012 Openstack, LLC
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""Handle the uploading and downloading of images via Glance."""

import cPickle as pickle
try:
    import json
except ImportError:
    import simplejson as json
import os
import shutil

import XenAPIPlugin

import utils

#FIXME(sirp): should this use pluginlib from 5.6?
from pluginlib_nova import *
configure_logging('hacks')


def _copy_vdis(sr_path, staging_path, vdi_uuids):
    seq_num = 0
    for vdi_uuid in vdi_uuids:
        src = os.path.join(sr_path, "%s.vhd" % vdi_uuid)
        dst = os.path.join(staging_path, "%d.vhd" % seq_num)
        shutil.copyfile(src, dst)
        seq_num += 1


def safe_copy_vdis(session, args):
    params = pickle.loads(exists(args, 'params'))
    sr_path = params["sr_path"]
    vdi_uuids = params["vdi_uuids"]
    uuid_stack = params["uuid_stack"]

    staging_path = utils.make_staging_area(sr_path)
    try:
        _copy_vdis(sr_path, staging_path, vdi_uuids)
        imported_vhds = utils.import_vhds(sr_path, staging_path, uuid_stack)
    finally:
        utils.cleanup_staging_area(staging_path)

    # Right now, it's easier to return a single string via XenAPI,
    # so we'll json encode the list of VHDs.
    return json.dumps(imported_vhds)


if __name__ == '__main__':
    XenAPIPlugin.dispatch({'safe_copy_vdis': safe_copy_vdis})
