#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'LOCALBRANCH', 'revision_id': 'LOCALREVISION',
                'revno': 0}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info

# below this line automatically generated by setup.py

YEAR = '2011'
COUNT = '1-dev'


def string():
    return '.'.join([YEAR, COUNT])


def vcs_version_string():
    return "%s:%s" % (version_info['branch_nick'], version_info['revision_id'])


def string_with_vcs():
    return "%s-%s" % (string(), vcs_version_string())
